<?php

namespace Tests\Feature;

use App\Models\News;
use App\Models\SalonSetting;
use App\Models\TopPageSection;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class NewsAdminTest extends TestCase
{
    use RefreshDatabase;

    private function admin(): User
    {
        return User::factory()->create();
    }

    private function createNews(array $overrides = []): News
    {
        return News::query()->create(array_merge([
            'title' => '元のタイトル',
            'slug' => 'original-title',
            'body' => "本文です。\n複数行もあります。",
            'category' => 'other',
            'is_published' => true,
            'published_at' => now()->startOfMinute(),
            'display_order' => 1,
        ], $overrides));
    }

    public function test_news_index_shows_card_ui_and_sticky_save(): void
    {
        $news = $this->createNews();

        $html = $this->actingAs($this->admin())
            ->get(route('admin.news.index'))
            ->assertOk()
            ->getContent();

        $this->assertStringContainsString('id="news-bulk-form"', $html);
        $this->assertStringContainsString('grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3', $html);
        $this->assertStringContainsString('id="news-add-card"', $html);
        $this->assertStringContainsString('data-news-add', $html);
        $this->assertStringContainsString('data-news-add-top', $html);
        $this->assertStringContainsString('お知らせを追加', $html);
        $this->assertStringContainsString('カードを追加し、保存で登録できます。', $html);
        $this->assertStringContainsString('data-news-drag-handle', $html);
        $this->assertStringContainsString('data-news-card-title', $html);
        $this->assertStringContainsString('元のタイトル', $html);
        $this->assertStringContainsString('admin-required-badge', $html);
        $this->assertStringContainsString('必須', $html);
        $this->assertStringContainsString('お知らせの種類', $html);
        $this->assertStringContainsString('name="news['.$news->id.'][category]"', $html);
        $this->assertStringContainsString('name="news['.$news->id.'][title]"', $html);
        $this->assertLessThan(
            strpos($html, 'name="news['.$news->id.'][title]"'),
            strpos($html, 'name="news['.$news->id.'][category]"')
        );
        $this->assertStringContainsString('data-news-title-input', $html);
        $this->assertStringContainsString('suggestedTitleForCategory', $html);
        $this->assertStringContainsString('applySuggestedTitle', $html);
        $this->assertStringContainsString('initializeTitleAutoState', $html);
        $this->assertStringContainsString('isAutoGeneratedTitle', $html);
        $this->assertStringContainsString('☆臨時休業のお知らせ☆', $html);
        $this->assertStringContainsString('news-category-choices', $html);
        $this->assertStringContainsString('定休日', $html);
        $this->assertStringContainsString('臨時休業', $html);
        $this->assertStringContainsString('data-news-closed-calendar', $html);
        $this->assertStringContainsString('data-news-weekday-wrap', $html);
        $this->assertStringContainsString('news-weekday-choices', $html);
        $this->assertStringContainsString('name="news['.$news->id.'][body]"', $html);
        $this->assertStringContainsString('name="news['.$news->id.'][published_at]"', $html);
        $this->assertStringContainsString('aria-label="公開状態"', $html);
        $this->assertStringContainsString('name="news['.$news->id.'][is_published]"', $html);
        $this->assertStringContainsString('admin-segmented-input', $html);
        $this->assertStringContainsString('>公開</span>', $html);
        $this->assertStringContainsString('>非公開</span>', $html);
        $this->assertStringContainsString('sticky top-0', $html);
        $this->assertStringContainsString('data-admin-confirm-trigger', $html);
        $this->assertStringContainsString('data-confirm-form="news-bulk-form"', $html);
        $this->assertStringContainsString('data-confirm-submit-label="保存する"', $html);
        $this->assertStringContainsString('data-news-title-input', $html);
        $this->assertStringContainsString('syncCardHeading', $html);
        $this->assertStringContainsString("emptyHeading = '新規お知らせ'", $html);
        $this->assertStringNotContainsString('id="news-create-modal"', $html);
        $this->assertStringNotContainsString('id="news-edit-modal"', $html);
        $this->assertStringNotContainsString('data-open-news-create', $html);
        $this->assertStringNotContainsString('data-open-news-edit', $html);
        $this->assertStringNotContainsString('ありません', $html);
    }

    public function test_news_index_shows_add_card_when_empty(): void
    {
        $html = $this->actingAs($this->admin())
            ->get(route('admin.news.index'))
            ->assertOk()
            ->getContent();

        $this->assertStringContainsString('id="news-add-card"', $html);
        $this->assertStringContainsString('data-news-add-top', $html);
        $this->assertStringContainsString('お知らせを追加', $html);
        $this->assertStringNotContainsString('ありません', $html);
    }

    public function test_bulk_update_creates_updates_and_deletes_news(): void
    {
        $keep = $this->createNews([
            'title' => '残す',
            'slug' => 'keep',
            'display_order' => 1,
            'is_published' => true,
        ]);
        $remove = $this->createNews([
            'title' => '消す',
            'slug' => 'remove',
            'display_order' => 2,
        ]);

        $this->actingAs($this->admin())
            ->put(route('admin.news.update'), [
                'news' => [
                    $keep->id => [
                        'title' => '更新後',
                        'body' => '更新本文',
                        'category' => 'other',
                        'published_at' => '2026-08-01T10:00',
                        'is_published' => '0',
                        'display_order' => 2,
                    ],
                ],
                'new_news' => [
                    'new_1' => [
                        'title' => '新規お知らせ',
                        'body' => "新規本文です。\n複数行。",
                        'category' => 'important',
                        'published_at' => '2026-08-02T12:00',
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
                'deleted_ids' => [$remove->id],
            ])
            ->assertRedirect(route('admin.news.index'))
            ->assertSessionHas('success', 'お知らせを保存しました。');

        $this->assertDatabaseMissing('news', ['id' => $remove->id]);

        $keep->refresh();
        $this->assertSame('更新後', $keep->title);
        $this->assertSame('更新本文', $keep->body);
        $this->assertSame('other', $keep->category);
        $this->assertFalse($keep->is_published);
        $this->assertSame(2, $keep->display_order);
        $this->assertSame('2026-08-01 10:00:00', $keep->published_at?->format('Y-m-d H:i:s'));

        $created = News::query()->where('title', '新規お知らせ')->first();
        $this->assertNotNull($created);
        $this->assertSame(1, $created->display_order);
        $this->assertTrue($created->is_published);
        $this->assertSame('important', $created->category);
        $this->assertNotSame('', (string) $created->slug);
    }

    public function test_holiday_category_saves_weekdays_and_shows_on_public_detail(): void
    {
        SalonSetting::current();

        $news = $this->createNews([
            'title' => '8月定休日',
            'slug' => 'august-closed',
            'category' => 'other',
            'is_published' => true,
            'published_at' => now()->subHour(),
        ]);
        $news->closedDates()->create(['closed_date' => '2026-08-04']);

        $this->actingAs($this->admin())
            ->put(route('admin.news.update'), [
                'news' => [
                    $news->id => [
                        'title' => '8月定休日',
                        'body' => 'ご理解のほどよろしくお願いします。',
                        'category' => 'holiday',
                        'closed_weekdays' => ['1', '2'],
                        'closed_dates' => ['2026-08-04'],
                        'published_at' => now()->subHour()->format('Y-m-d\TH:i'),
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'));

        $news->refresh();
        $this->assertSame('holiday', $news->category);
        $this->assertSame([1, 2], $news->closedWeekdays()->orderBy('weekday')->pluck('weekday')->all());
        $this->assertSame(0, $news->closedDates()->count());

        $editHtml = $this->actingAs($this->admin())
            ->get(route('admin.news.index'))
            ->assertOk()
            ->getContent();
        $this->assertStringContainsString('data-news-weekday-wrap', $editHtml);
        $this->assertStringContainsString('name="news['.$news->id.'][closed_weekdays][]"', $editHtml);
        $this->assertStringContainsString('value="1"', $editHtml);

        $showHtml = $this->get(route('news.show', $news->slug))
            ->assertOk()
            ->getContent();
        $this->assertStringContainsString('定休日は毎週月曜日・火曜日です。', $showHtml);
        $this->assertStringNotContainsString('以下の日程は定休日となります。', $showHtml);
        $this->assertLessThan(
            strpos($showHtml, 'ご理解のほどよろしくお願いします。'),
            strpos($showHtml, '定休日は毎週月曜日・火曜日です。')
        );
    }

    public function test_temporary_closure_category_also_saves_closed_dates(): void
    {
        $news = $this->createNews([
            'title' => '臨時休業のお知らせ',
            'slug' => 'temporary-closure',
            'category' => 'other',
            'is_published' => true,
            'published_at' => now()->subHour(),
        ]);
        $news->closedWeekdays()->create(['weekday' => 1]);

        $this->actingAs($this->admin())
            ->put(route('admin.news.update'), [
                'news' => [
                    $news->id => [
                        'title' => '臨時休業のお知らせ',
                        'body' => '臨時休業します。',
                        'category' => 'temporary_closure',
                        'closed_dates' => ['2026-09-01', '2026-09-02'],
                        'closed_weekdays' => ['1'],
                        'published_at' => now()->subHour()->format('Y-m-d\TH:i'),
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'));

        $news->refresh();
        $this->assertSame('temporary_closure', $news->category);
        $this->assertSame(
            ['2026-09-01', '2026-09-02'],
            $news->closedDates()->orderBy('closed_date')->pluck('closed_date')->map->toDateString()->all()
        );
        $this->assertSame(0, $news->closedWeekdays()->count());

        $showHtml = $this->get(route('news.show', $news->slug))->assertOk()->getContent();
        $this->assertStringContainsString('臨時休業', $showHtml);
        $this->assertStringContainsString('以下の日程は臨時休業となります。', $showHtml);
        $this->assertStringContainsString('9月1日（', $showHtml);
        $this->assertStringNotContainsString('>休業日</', $showHtml);
        $this->assertLessThan(strpos($showHtml, '臨時休業します。'), strpos($showHtml, '以下の日程は臨時休業となります。'));

        $this->assertSame(
            ['2026-09-01', '2026-09-02'],
            \App\Models\NewsClosedDate::publishedClosedDateValues()->all()
        );
    }

    public function test_legacy_closed_category_migrates_to_holiday_keeping_dates(): void
    {
        $news = $this->createNews([
            'title' => '旧種別',
            'slug' => 'legacy-closed',
            'category' => 'other',
            'is_published' => true,
        ]);
        \Illuminate\Support\Facades\DB::table('news')->where('id', $news->id)->update(['category' => 'closed']);
        $news->closedDates()->create(['closed_date' => '2026-08-20']);

        $migration = require database_path('migrations/2026_08_09_000027_split_news_closed_category.php');
        $migration->up();

        $news->refresh();
        $this->assertSame('holiday', $news->category);
        $this->assertTrue($news->isClosedAnnouncement());
        $this->assertSame(1, $news->closedDates()->count());
        $this->assertSame('2026-08-20', $news->closedDates()->first()->closed_date->toDateString());
    }

    public function test_non_closed_category_does_not_keep_closed_dates(): void
    {
        $news = $this->createNews([
            'title' => '料金改定',
            'slug' => 'price-change',
            'category' => 'holiday',
            'is_published' => true,
        ]);
        $news->closedDates()->create(['closed_date' => '2026-08-10']);
        $news->closedWeekdays()->create(['weekday' => 2]);

        $this->actingAs($this->admin())
            ->put(route('admin.news.update'), [
                'news' => [
                    $news->id => [
                        'title' => '料金改定',
                        'body' => '料金を改定します。',
                        'category' => 'price',
                        'closed_dates' => ['2026-08-10'],
                        'closed_weekdays' => ['2'],
                        'published_at' => '2026-08-01T10:00',
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'));

        $this->assertSame('price', $news->fresh()->category);
        $this->assertSame(0, $news->closedDates()->count());
        $this->assertSame(0, $news->closedWeekdays()->count());
    }

    public function test_bulk_update_requires_mandatory_fields_for_new_news(): void
    {
        $this->actingAs($this->admin())
            ->from(route('admin.news.index'))
            ->put(route('admin.news.update'), [
                'new_news' => [
                    'new_1' => [
                        'title' => '',
                        'body' => '',
                        'category' => 'other',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'))
            ->assertSessionHasErrors([
                'new_news.new_1.title',
                'new_news.new_1.published_at',
                'new_news.new_1.is_published',
            ])
            ->assertSessionDoesntHaveErrors(['new_news.new_1.body']);
    }

    public function test_news_can_be_saved_without_body(): void
    {
        $this->actingAs($this->admin())
            ->put(route('admin.news.update'), [
                'new_news' => [
                    'new_1' => [
                        'title' => '本文なしお知らせ',
                        'body' => '',
                        'category' => 'other',
                        'published_at' => '2026-08-01T10:00',
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'))
            ->assertSessionHasNoErrors();

        $news = News::query()->where('title', '本文なしお知らせ')->first();
        $this->assertNotNull($news);
        $this->assertSame('', $news->body);

        $this->get(route('news.show', $news->slug))
            ->assertOk()
            ->assertSee('本文なしお知らせ', false)
            ->assertDontSee('prose prose-neutral', false);
    }

    public function test_holiday_requires_at_least_one_weekday(): void
    {
        $this->actingAs($this->admin())
            ->from(route('admin.news.index'))
            ->put(route('admin.news.update'), [
                'new_news' => [
                    'new_1' => [
                        'title' => '定休日',
                        'body' => '休業します。',
                        'category' => 'holiday',
                        'closed_weekdays' => [],
                        'published_at' => '2026-08-01T10:00',
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'))
            ->assertSessionHasErrors(['new_news.new_1.closed_weekdays']);
    }

    public function test_temporary_closure_requires_at_least_one_closed_date(): void
    {
        $this->actingAs($this->admin())
            ->from(route('admin.news.index'))
            ->put(route('admin.news.update'), [
                'new_news' => [
                    'new_1' => [
                        'title' => '臨時休業',
                        'body' => '休業します。',
                        'category' => 'temporary_closure',
                        'closed_dates' => [],
                        'published_at' => '2026-08-01T10:00',
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'))
            ->assertSessionHasErrors(['new_news.new_1.closed_dates']);
    }

    public function test_new_card_markup_leaves_publish_state_unselected(): void
    {
        $html = $this->actingAs($this->admin())
            ->get(route('admin.news.index'))
            ->assertOk()
            ->getContent();

        $this->assertStringContainsString('novalidate', $html);
        $this->assertStringContainsString(
            "'<input type=\"radio\" name=\"new_news[' + key + '][is_published]\" value=\"1\" class=\"admin-segmented-input\" data-news-is-published>' +",
            $html
        );
        $this->assertStringNotContainsString(
            "'<input type=\"radio\" name=\"new_news[' + key + '][is_published]\" value=\"1\" class=\"admin-segmented-input\" data-news-is-published checked>' +",
            $html
        );
        $this->assertStringContainsString('fillPublishedAtIfEmpty', $html);
        $this->assertStringContainsString('const appTimezone =', $html);
        $this->assertStringContainsString('Asia\/Tokyo', $html);
        $this->assertStringContainsString('data-news-published-at', $html);
    }

    public function test_bulk_update_preserves_input_on_validation_errors(): void
    {
        $news = $this->createNews(['title' => '既存', 'slug' => 'existing']);

        $this->actingAs($this->admin())
            ->from(route('admin.news.index'))
            ->put(route('admin.news.update'), [
                'news' => [
                    $news->id => [
                        'title' => '',
                        'body' => '残す本文',
                        'category' => 'other',
                        'published_at' => '2026-08-01T09:00',
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
                'new_news' => [
                    'new_1' => [
                        'title' => '新規入力途中',
                        'body' => '',
                        'category' => 'hours',
                        'published_at' => '2026-08-03T11:00',
                        'is_published' => '0',
                        'display_order' => 2,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'))
            ->assertSessionHasErrors(['news.'.$news->id.'.title'])
            ->assertSessionDoesntHaveErrors(['new_news.new_1.body']);

        $this->assertSame('残す本文', session()->getOldInput('news.'.$news->id.'.body'));
        $this->assertSame('新規入力途中', session()->getOldInput('new_news.new_1.title'));
        $this->assertSame('2026-08-03T11:00', session()->getOldInput('new_news.new_1.published_at'));

        $html = $this->actingAs($this->admin())
            ->get(route('admin.news.index'))
            ->assertOk()
            ->getContent();

        $this->assertStringContainsString('残す本文', $html);
        $this->assertStringContainsString('新規入力途中', $html);
        $this->assertStringContainsString('name="new_news[new_1][title]"', $html);
        $this->assertStringContainsString('2026-08-03T11:00', $html);
    }

    public function test_validation_error_preserves_prepended_new_news_card_order(): void
    {
        $existing1 = $this->createNews([
            'title' => '既存1',
            'slug' => 'existing-1',
            'display_order' => 1,
        ]);
        $existing2 = $this->createNews([
            'title' => '既存2',
            'slug' => 'existing-2',
            'display_order' => 2,
        ]);

        $html = $this->actingAs($this->admin())
            ->followingRedirects()
            ->from(route('admin.news.index'))
            ->put(route('admin.news.update'), [
                'news' => [
                    $existing1->id => [
                        'title' => '既存1',
                        'body' => '本文1',
                        'category' => 'other',
                        'published_at' => '2026-08-01T10:00',
                        'is_published' => '1',
                        'display_order' => 2,
                    ],
                    $existing2->id => [
                        'title' => '既存2',
                        'body' => '本文2',
                        'category' => 'other',
                        'published_at' => '2026-08-01T11:00',
                        'is_published' => '1',
                        'display_order' => 3,
                    ],
                ],
                'new_news' => [
                    'new_1' => [
                        'title' => '先頭の新規',
                        'body' => '新規本文',
                        'category' => 'other',
                        'published_at' => '',
                        'is_published' => '0',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertOk()
            ->assertSee('先頭の新規', false)
            ->getContent();

        preg_match('/id="news-grid"(.*?)<div\s+id="news-add-card"/s', $html, $matches);
        $this->assertNotEmpty($matches);
        $grid = $matches[1];

        $posNew = strpos($grid, 'data-news-new');
        $posExisting1 = strpos($grid, 'data-news-id="'.$existing1->id.'"');
        $posExisting2 = strpos($grid, 'data-news-id="'.$existing2->id.'"');

        $this->assertNotFalse($posNew);
        $this->assertNotFalse($posExisting1);
        $this->assertNotFalse($posExisting2);
        $this->assertLessThan($posExisting1, $posNew);
        $this->assertLessThan($posExisting2, $posExisting1);
    }

    public function test_bulk_update_normalizes_display_order(): void
    {
        $a = $this->createNews(['title' => 'A', 'slug' => 'a', 'display_order' => 10]);
        $b = $this->createNews(['title' => 'B', 'slug' => 'b', 'display_order' => 20]);

        $this->actingAs($this->admin())
            ->put(route('admin.news.update'), [
                'news' => [
                    $b->id => [
                        'title' => 'B',
                        'body' => 'body-b',
                        'category' => 'other',
                        'published_at' => '2026-08-01T10:00',
                        'display_order' => 1,
                        'is_published' => '1',
                    ],
                    $a->id => [
                        'title' => 'A',
                        'body' => 'body-a',
                        'category' => 'other',
                        'published_at' => '2026-08-01T10:00',
                        'display_order' => 2,
                        'is_published' => '1',
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'));

        $this->assertSame(1, $b->fresh()->display_order);
        $this->assertSame(2, $a->fresh()->display_order);
    }

    public function test_guest_cannot_access_news_admin(): void
    {
        $this->get(route('admin.news.index'))->assertRedirect();
        $this->put(route('admin.news.update'), [])->assertRedirect();
    }

    public function test_public_news_honors_display_order_and_published_rules(): void
    {
        SalonSetting::current();
        TopPageSection::ensureDefaults();

        $this->createNews([
            'title' => '後で表示',
            'slug' => 'second',
            'display_order' => 2,
            'is_published' => true,
            'published_at' => now()->subDay(),
        ]);
        $this->createNews([
            'title' => '先に表示',
            'slug' => 'first',
            'display_order' => 1,
            'is_published' => true,
            'published_at' => now()->subDays(5),
        ]);
        $this->createNews([
            'title' => '非公開',
            'slug' => 'draft',
            'display_order' => 0,
            'is_published' => false,
            'published_at' => now(),
        ]);
        $this->createNews([
            'title' => '未来公開',
            'slug' => 'future',
            'display_order' => 0,
            'is_published' => true,
            'published_at' => now()->addDay(),
        ]);

        $homeHtml = $this->get(route('home'))->assertOk()->getContent();
        $this->assertStringContainsString('先に表示', $homeHtml);
        $this->assertStringContainsString('後で表示', $homeHtml);
        $this->assertStringNotContainsString('非公開', $homeHtml);
        $this->assertStringNotContainsString('未来公開', $homeHtml);
        $this->assertLessThan(strpos($homeHtml, '後で表示'), strpos($homeHtml, '先に表示'));

        $listHtml = $this->get(route('news.index'))->assertOk()->getContent();
        $this->assertStringContainsString('先に表示', $listHtml);
        $this->assertLessThan(strpos($listHtml, '後で表示'), strpos($listHtml, '先に表示'));

        $this->get(route('news.show', 'first'))->assertOk()->assertSee('先に表示');
        $this->get(route('news.show', 'draft'))->assertNotFound();
        $this->get(route('news.show', 'future'))->assertNotFound();
    }
}
