<?php

namespace Tests\Feature;

use App\Models\DesignSetting;
use App\Models\News;
use App\Models\SalonSetting;
use App\Models\TopPageSection;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class NewsAdminTest extends TestCase
{
    use RefreshDatabase;

    private function admin(): User
    {
        return User::factory()->create();
    }

    private function createNews(array $overrides = []): News
    {
        return News::query()->create(array_merge([
            'title' => '元のタイトル',
            'slug' => 'original-title',
            'body' => "本文です。\n複数行もあります。",
            'category' => 'other',
            'is_published' => true,
            'published_at' => now()->startOfMinute(),
            'display_order' => 1,
        ], $overrides));
    }

    public function test_news_index_shows_card_ui_and_sticky_save(): void
    {
        $news = $this->createNews();

        $html = $this->actingAs($this->admin())
            ->get(route('admin.news.index'))
            ->assertOk()
            ->getContent();

        $this->assertStringContainsString('id="news-bulk-form"', $html);
        $this->assertStringContainsString('grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3', $html);
        $this->assertStringContainsString('id="news-add-card"', $html);
        $this->assertStringContainsString('data-news-add', $html);
        $this->assertStringContainsString('data-news-add-top', $html);
        $this->assertStringContainsString('お知らせを追加', $html);
        $this->assertStringContainsString('カードを追加し、保存で登録できます。', $html);
        $this->assertStringContainsString('data-news-drag-handle', $html);
        $this->assertStringContainsString('data-news-card-title', $html);
        $this->assertStringContainsString('元のタイトル', $html);
        $this->assertStringContainsString('admin-required-badge', $html);
        $this->assertStringContainsString('必須', $html);
        $this->assertStringContainsString('お知らせの種類', $html);
        $this->assertStringContainsString('name="news['.$news->id.'][category]"', $html);
        $this->assertStringContainsString('name="news['.$news->id.'][title]"', $html);
        $this->assertLessThan(
            strpos($html, 'name="news['.$news->id.'][title]"'),
            strpos($html, 'name="news['.$news->id.'][category]"')
        );
        $this->assertStringContainsString('data-news-title-input', $html);
        $this->assertStringContainsString('suggestedTitleForCategory', $html);
        $this->assertStringContainsString('applySuggestedTitle', $html);
        $this->assertStringContainsString('initializeTitleAutoState', $html);
        $this->assertStringContainsString('isAutoGeneratedTitle', $html);
        $this->assertStringContainsString('☆臨時休業のお知らせ☆', $html);
        $this->assertStringContainsString('news-category-choices', $html);
        $this->assertStringContainsString('定休日', $html);
        $this->assertStringContainsString('臨時休業', $html);
        $this->assertStringContainsString('営業カレンダー設定', $html);
        $this->assertStringContainsString('対象期間', $html);
        $this->assertStringContainsString('name="calendar_holiday_color"', $html);
        $this->assertStringContainsString('name="calendar_temporary_color"', $html);
        $this->assertStringContainsString('name="calendar_hours_color"', $html);
        $this->assertStringContainsString('data-news-calendar-colors-reset', $html);
        $this->assertStringContainsString('data-confirm-callback="news-calendar-colors-reset"', $html);
        $this->assertStringContainsString('初期値に戻す', $html);
        $this->assertStringContainsString('data-news-hours-wrap', $html);
        $this->assertStringContainsString('applyRegularHoursDefaults', $html);
        $this->assertStringContainsString('regularBusinessHours', $html);
        $this->assertStringContainsString('data-news-closed-calendar', $html);
        $this->assertStringContainsString('data-news-weekday-wrap', $html);
        $this->assertStringContainsString('news-weekday-choices', $html);
        $this->assertStringContainsString('name="news['.$news->id.'][body]"', $html);
        $this->assertStringContainsString('name="news['.$news->id.'][published_at]"', $html);
        $this->assertStringContainsString('aria-label="公開状態"', $html);
        $this->assertStringContainsString('name="news['.$news->id.'][is_published]"', $html);
        $this->assertStringContainsString('admin-segmented-input', $html);
        $this->assertStringContainsString('>公開</span>', $html);
        $this->assertStringContainsString('>非公開</span>', $html);
        $this->assertStringContainsString('sticky top-0', $html);
        $this->assertStringContainsString('data-admin-confirm-trigger', $html);
        $this->assertStringContainsString('data-confirm-form="news-bulk-form"', $html);
        $this->assertStringContainsString('data-confirm-submit-label="保存する"', $html);
        $this->assertStringContainsString('data-news-title-input', $html);
        $this->assertStringContainsString('syncCardHeading', $html);
        $this->assertStringContainsString("emptyHeading = '新規お知らせ'", $html);
        $this->assertStringNotContainsString('id="news-create-modal"', $html);
        $this->assertStringNotContainsString('id="news-edit-modal"', $html);
        $this->assertStringNotContainsString('data-open-news-create', $html);
        $this->assertStringNotContainsString('data-open-news-edit', $html);
        $this->assertStringNotContainsString('ありません', $html);
    }

    public function test_news_index_shows_add_card_when_empty(): void
    {
        $html = $this->actingAs($this->admin())
            ->get(route('admin.news.index'))
            ->assertOk()
            ->getContent();

        $this->assertStringContainsString('id="news-add-card"', $html);
        $this->assertStringContainsString('data-news-add-top', $html);
        $this->assertStringContainsString('お知らせを追加', $html);
        $this->assertStringNotContainsString('ありません', $html);
    }

    public function test_bulk_update_creates_updates_and_deletes_news(): void
    {
        $keep = $this->createNews([
            'title' => '残す',
            'slug' => 'keep',
            'display_order' => 1,
            'is_published' => true,
        ]);
        $remove = $this->createNews([
            'title' => '消す',
            'slug' => 'remove',
            'display_order' => 2,
        ]);

        $this->actingAs($this->admin())
            ->put(route('admin.news.update'), [
                'news' => [
                    $keep->id => [
                        'title' => '更新後',
                        'body' => '更新本文',
                        'category' => 'other',
                        'published_at' => '2026-08-01T10:00',
                        'is_published' => '0',
                        'display_order' => 2,
                    ],
                ],
                'new_news' => [
                    'new_1' => [
                        'title' => '新規お知らせ',
                        'body' => "新規本文です。\n複数行。",
                        'category' => 'important',
                        'published_at' => '2026-08-02T12:00',
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
                'deleted_ids' => [$remove->id],
            ])
            ->assertRedirect(route('admin.news.index'))
            ->assertSessionHas('success', 'お知らせを保存しました。');

        $this->assertDatabaseMissing('news', ['id' => $remove->id]);

        $keep->refresh();
        $this->assertSame('更新後', $keep->title);
        $this->assertSame('更新本文', $keep->body);
        $this->assertSame('other', $keep->category);
        $this->assertFalse($keep->is_published);
        $this->assertSame(2, $keep->display_order);
        $this->assertSame('2026-08-01 10:00:00', $keep->published_at?->format('Y-m-d H:i:s'));

        $created = News::query()->where('title', '新規お知らせ')->first();
        $this->assertNotNull($created);
        $this->assertSame(1, $created->display_order);
        $this->assertTrue($created->is_published);
        $this->assertSame('important', $created->category);
        $this->assertNotSame('', (string) $created->slug);
    }

    public function test_holiday_category_uses_salon_closed_days_on_public_detail(): void
    {
        $salon = SalonSetting::current();
        $salon->closedWeekdays()->delete();
        $salon->closedNthWeekdays()->delete();
        $salon->closedWeekdays()->create(['weekday' => 2]);
        $salon->closedNthWeekdays()->create([
            'week_of_month' => 3,
            'weekday' => 3,
        ]);

        $news = $this->createNews([
            'title' => '8月定休日',
            'slug' => 'august-closed',
            'category' => 'other',
            'is_published' => true,
            'published_at' => now()->subHour(),
        ]);
        $news->closedDates()->create(['closed_date' => '2026-08-04']);
        $news->closedWeekdays()->create(['weekday' => 1]);

        $this->actingAs($this->admin())
            ->put(route('admin.news.update'), [
                'news' => [
                    $news->id => [
                        'title' => '8月定休日',
                        'body' => 'ご理解のほどよろしくお願いします。',
                        'category' => 'holiday',
                        'holiday_period_type' => '3_months',
                        'holiday_period_from' => '2026-08-01',
                        'holiday_period_to' => '2026-10-31',
                        'closed_weekdays' => ['2'],
                        'closed_nth' => [
                            ['week' => 3, 'weekday' => 3],
                        ],
                        'closed_dates' => ['2026-08-04'],
                        'published_at' => now()->subHour()->format('Y-m-d\TH:i'),
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'));

        $news->refresh();
        $this->assertSame('holiday', $news->category);
        $this->assertSame('3_months', $news->holiday_period_type);
        $this->assertSame('2026-08-01', $news->holiday_period_from?->toDateString());
        $this->assertSame('2026-10-31', $news->holiday_period_to?->toDateString());
        $this->assertSame([2], $news->closedWeekdayValues());
        $this->assertSame([['week' => 3, 'weekday' => 3]], $news->closedNthWeekdayRules());
        $this->assertSame(0, $news->closedDates()->count());

        $showHtml = $this->get(route('news.show', $news->slug))
            ->assertOk()
            ->getContent();
        $this->assertStringContainsString('定休日は毎週火曜日・第3水曜日です。', $showHtml);
        $this->assertStringContainsString('対象期間：2026/08/01 ～ 2026/10/31', $showHtml);
        $this->assertStringNotContainsString('以下の日程は定休日となります。', $showHtml);
        $this->assertLessThan(
            strpos($showHtml, 'ご理解のほどよろしくお願いします。'),
            strpos($showHtml, '定休日は毎週火曜日・第3水曜日です。')
        );
    }

    public function test_hours_category_saves_change_date_and_times_and_calendar_colors(): void
    {
        $news = $this->createNews([
            'title' => '営業時間変更のお知らせ',
            'slug' => 'hours-change',
            'category' => 'other',
            'is_published' => true,
            'published_at' => now()->subHour(),
        ]);

        $this->actingAs($this->admin())
            ->put(route('admin.news.update'), [
                'calendar_holiday_color' => '#CCD5C0',
                'calendar_temporary_color' => '#E2D8CE',
                'calendar_hours_color' => '#D8C6B0',
                'news' => [
                    $news->id => [
                        'title' => '営業時間変更のお知らせ',
                        'body' => 'ご理解をお願いします。',
                        'category' => 'hours',
                        'hours_change_date' => '2026-08-12',
                        'hours_start_time' => '10:00',
                        'hours_end_time' => '19:00',
                        'published_at' => now()->subHour()->format('Y-m-d\TH:i'),
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'));

        $news->refresh();
        $this->assertSame('hours', $news->category);
        $this->assertSame('2026-08-12', $news->hours_change_date?->toDateString());
        $this->assertSame('10:00', $news->hoursStartTimeLabel());
        $this->assertSame('19:00', $news->hoursEndTimeLabel());
        $this->assertSame('営業時間変更　10:00〜19:00', $news->hoursChangeNoteDetail());
        $this->assertSame(0, $news->closedDates()->count());
        $this->assertSame(0, $news->closedWeekdays()->count());

        $design = DesignSetting::current()->fresh();
        $this->assertSame('#ccd5c0', $design->calendar_holiday_color);
        $this->assertSame('#e2d8ce', $design->calendar_temporary_color);
        $this->assertSame('#d8c6b0', $design->calendar_hours_color);
        $this->assertSame('#ccd5c0', $design->cssVariables()['--site-calendar-holiday-bg']);
    }

    public function test_regular_business_hours_defaults_follow_weekday_weekend_and_holiday(): void
    {
        $setting = SalonSetting::current();
        $setting->forceFill([
            'weekday_open_time' => '10:00:00',
            'weekday_close_time' => '20:00:00',
            'weekend_open_time' => '09:00:00',
            'weekend_close_time' => '19:00:00',
        ])->save();

        $weekday = $setting->regularHoursForDate(\Illuminate\Support\Carbon::parse('2026-08-12')); // Wed
        $this->assertSame('weekday', $weekday['bucket']);
        $this->assertSame('10:00', $weekday['open']);
        $this->assertSame('20:00', $weekday['close']);

        $saturday = $setting->regularHoursForDate(\Illuminate\Support\Carbon::parse('2026-08-15'));
        $this->assertSame('weekend', $saturday['bucket']);
        $this->assertSame('09:00', $saturday['open']);
        $this->assertSame('19:00', $saturday['close']);

        $mountainDay = $setting->regularHoursForDate(\Illuminate\Support\Carbon::parse('2026-08-11')); // Tue holiday
        $this->assertSame('weekend', $mountainDay['bucket']);
        $this->assertSame('09:00', $mountainDay['open']);

        $html = $this->actingAs($this->admin())
            ->get(route('admin.news.index'))
            ->assertOk()
            ->getContent();
        $this->assertStringContainsString('"open":"10:00"', $html);
        $this->assertStringContainsString('"open":"09:00"', $html);
        $this->assertStringContainsString('2026-08-11', $html);
    }

    public function test_existing_hours_news_keeps_saved_times_on_edit_form(): void
    {
        $setting = SalonSetting::current();
        $setting->forceFill([
            'weekday_open_time' => '10:00:00',
            'weekday_close_time' => '20:00:00',
            'weekend_open_time' => '09:00:00',
            'weekend_close_time' => '19:00:00',
        ])->save();

        $news = $this->createNews([
            'title' => '営業時間変更のお知らせ',
            'slug' => 'hours-saved',
            'category' => 'hours',
            'hours_change_date' => '2026-08-12',
            'hours_start_time' => '11:30:00',
            'hours_end_time' => '16:00:00',
            'is_published' => true,
            'published_at' => now()->subHour(),
        ]);

        $html = $this->actingAs($this->admin())
            ->get(route('admin.news.index'))
            ->assertOk()
            ->getContent();

        $this->assertStringContainsString('name="news['.$news->id.'][hours_start_time]"', $html);
        $this->assertStringContainsString('value="11:30"', $html);
        $this->assertStringContainsString('value="16:00"', $html);
        $this->assertStringContainsString('保存済みの変更営業時間を表示しています', $html);
    }

    public function test_hours_change_does_not_mutate_salon_regular_hours(): void
    {
        $setting = SalonSetting::current();
        $setting->forceFill([
            'weekday_open_time' => '10:00:00',
            'weekday_close_time' => '20:00:00',
            'weekend_open_time' => '09:00:00',
            'weekend_close_time' => '19:00:00',
        ])->save();

        $news = $this->createNews([
            'title' => '営業時間変更のお知らせ',
            'slug' => 'hours-no-mutate',
            'category' => 'other',
        ]);

        $this->actingAs($this->admin())
            ->put(route('admin.news.update'), [
                'news' => [
                    $news->id => [
                        'title' => '営業時間変更のお知らせ',
                        'body' => '',
                        'category' => 'hours',
                        'hours_change_date' => '2026-08-12',
                        'hours_start_time' => '12:00',
                        'hours_end_time' => '15:00',
                        'published_at' => now()->subHour()->format('Y-m-d\TH:i'),
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'));

        $setting->refresh();
        $this->assertSame('10:00', $setting->weekdayOpenTimeInputValue());
        $this->assertSame('20:00', $setting->weekdayCloseTimeInputValue());
        $this->assertSame('09:00', $setting->weekendOpenTimeInputValue());
        $this->assertSame('19:00', $setting->weekendCloseTimeInputValue());
        $this->assertSame("平日 10:00 - 20:00\n土日祝 9:00 - 19:00", $setting->businessHoursDisplayText());
    }

    public function test_hours_category_requires_change_date_and_times(): void
    {
        $news = $this->createNews([
            'title' => '営業時間変更のお知らせ',
            'slug' => 'hours-required',
            'category' => 'other',
        ]);

        $this->actingAs($this->admin())
            ->from(route('admin.news.index'))
            ->put(route('admin.news.update'), [
                'news' => [
                    $news->id => [
                        'title' => '営業時間変更のお知らせ',
                        'body' => '',
                        'category' => 'hours',
                        'published_at' => now()->subHour()->format('Y-m-d\TH:i'),
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'))
            ->assertSessionHasErrors([
                'news.'.$news->id.'.hours_change_date',
                'news.'.$news->id.'.hours_start_time',
                'news.'.$news->id.'.hours_end_time',
            ]);
    }

    public function test_temporary_closure_category_also_saves_closed_dates(): void
    {
        $news = $this->createNews([
            'title' => '臨時休業のお知らせ',
            'slug' => 'temporary-closure',
            'category' => 'other',
            'is_published' => true,
            'published_at' => now()->subHour(),
        ]);
        $news->closedWeekdays()->create(['weekday' => 1]);

        $this->actingAs($this->admin())
            ->put(route('admin.news.update'), [
                'news' => [
                    $news->id => [
                        'title' => '臨時休業のお知らせ',
                        'body' => '臨時休業します。',
                        'category' => 'temporary_closure',
                        'closed_dates' => ['2026-09-01', '2026-09-02'],
                        'closed_weekdays' => ['1'],
                        'published_at' => now()->subHour()->format('Y-m-d\TH:i'),
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'));

        $news->refresh();
        $this->assertSame('temporary_closure', $news->category);
        $this->assertSame(
            ['2026-09-01', '2026-09-02'],
            $news->closedDates()->orderBy('closed_date')->pluck('closed_date')->map->toDateString()->all()
        );
        $this->assertSame(0, $news->closedWeekdays()->count());

        $showHtml = $this->get(route('news.show', $news->slug))->assertOk()->getContent();
        $this->assertStringContainsString('臨時休業', $showHtml);
        $this->assertStringContainsString('以下の日程は臨時休業となります。', $showHtml);
        $this->assertStringContainsString('9月1日（', $showHtml);
        $this->assertStringNotContainsString('>休業日</', $showHtml);
        $this->assertLessThan(strpos($showHtml, '臨時休業します。'), strpos($showHtml, '以下の日程は臨時休業となります。'));

        $this->assertSame(
            ['2026-09-01', '2026-09-02'],
            \App\Models\NewsClosedDate::publishedClosedDateValues()->all()
        );
    }

    public function test_legacy_closed_category_migrates_to_holiday_keeping_dates(): void
    {
        $news = $this->createNews([
            'title' => '旧種別',
            'slug' => 'legacy-closed',
            'category' => 'other',
            'is_published' => true,
        ]);
        \Illuminate\Support\Facades\DB::table('news')->where('id', $news->id)->update(['category' => 'closed']);
        $news->closedDates()->create(['closed_date' => '2026-08-20']);

        $migration = require database_path('migrations/2026_08_09_000027_split_news_closed_category.php');
        $migration->up();

        $news->refresh();
        $this->assertSame('holiday', $news->category);
        $this->assertTrue($news->isClosedAnnouncement());
        $this->assertSame(1, $news->closedDates()->count());
        $this->assertSame('2026-08-20', $news->closedDates()->first()->closed_date->toDateString());
    }

    public function test_non_closed_category_does_not_keep_closed_dates(): void
    {
        $news = $this->createNews([
            'title' => '料金改定',
            'slug' => 'price-change',
            'category' => 'holiday',
            'is_published' => true,
        ]);
        $news->closedDates()->create(['closed_date' => '2026-08-10']);
        $news->closedWeekdays()->create(['weekday' => 2]);

        $this->actingAs($this->admin())
            ->put(route('admin.news.update'), [
                'news' => [
                    $news->id => [
                        'title' => '料金改定',
                        'body' => '料金を改定します。',
                        'category' => 'price',
                        'closed_dates' => ['2026-08-10'],
                        'closed_weekdays' => ['2'],
                        'published_at' => '2026-08-01T10:00',
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'));

        $this->assertSame('price', $news->fresh()->category);
        $this->assertSame(0, $news->closedDates()->count());
        $this->assertSame(0, $news->closedWeekdays()->count());
    }

    public function test_bulk_update_requires_mandatory_fields_for_new_news(): void
    {
        $this->actingAs($this->admin())
            ->from(route('admin.news.index'))
            ->put(route('admin.news.update'), [
                'new_news' => [
                    'new_1' => [
                        'title' => '',
                        'body' => '',
                        'category' => 'other',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'))
            ->assertSessionHasErrors([
                'new_news.new_1.title',
                'new_news.new_1.published_at',
                'new_news.new_1.is_published',
            ])
            ->assertSessionDoesntHaveErrors(['new_news.new_1.body']);
    }

    public function test_news_can_be_saved_without_body(): void
    {
        $this->actingAs($this->admin())
            ->put(route('admin.news.update'), [
                'new_news' => [
                    'new_1' => [
                        'title' => '本文なしお知らせ',
                        'body' => '',
                        'category' => 'other',
                        'published_at' => '2026-08-01T10:00',
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'))
            ->assertSessionHasNoErrors();

        $news = News::query()->where('title', '本文なしお知らせ')->first();
        $this->assertNotNull($news);
        $this->assertSame('', $news->body);

        $this->get(route('news.show', $news->slug))
            ->assertOk()
            ->assertSee('本文なしお知らせ', false)
            ->assertDontSee('prose prose-neutral', false);
    }

    public function test_holiday_category_saves_closed_day_rules_from_salon_defaults(): void
    {
        $salon = SalonSetting::current();
        $salon->closedWeekdays()->delete();
        $salon->closedNthWeekdays()->delete();
        $salon->closedWeekdays()->create(['weekday' => 2]);
        $salon->closedNthWeekdays()->create([
            'week_of_month' => 3,
            'weekday' => 3,
        ]);

        $this->actingAs($this->admin())
            ->put(route('admin.news.update'), [
                'new_news' => [
                    'new_1' => [
                        'title' => '定休日',
                        'body' => '店舗情報の定休日をご確認ください。',
                        'category' => 'holiday',
                        'holiday_period_type' => '1_year',
                        'holiday_period_from' => '2026-09-01',
                        'holiday_period_to' => '2027-08-31',
                        'closed_weekdays' => ['2'],
                        'closed_nth' => [
                            ['week' => 3, 'weekday' => 3],
                        ],
                        'published_at' => '2026-08-01T10:00',
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'))
            ->assertSessionHasNoErrors();

        $news = News::query()->where('title', '定休日')->first();
        $this->assertNotNull($news);
        $this->assertSame('holiday', $news->category);
        $this->assertSame('1_year', $news->holiday_period_type);
        $this->assertSame('2026-09-01', $news->holiday_period_from?->toDateString());
        $this->assertSame('2027-08-31', $news->holiday_period_to?->toDateString());
        $this->assertSame([
            '2026-09', '2026-10', '2026-11', '2026-12',
            '2027-01', '2027-02', '2027-03', '2027-04',
            '2027-05', '2027-06', '2027-07', '2027-08',
        ], $news->holidayPeriodMonthKeys());
        $this->assertSame([2], $news->closedWeekdayValues());
        $this->assertSame([['week' => 3, 'weekday' => 3]], $news->closedNthWeekdayRules());
        $this->assertSame('定休日は毎週火曜日・第3水曜日です。', $news->closedDaysAnnouncementSentence());
    }

    public function test_holiday_category_requires_closed_day_rules(): void
    {
        $this->actingAs($this->admin())
            ->from(route('admin.news.index'))
            ->put(route('admin.news.update'), [
                'new_news' => [
                    'new_1' => [
                        'title' => '定休日',
                        'body' => '',
                        'category' => 'holiday',
                        'holiday_period_type' => '1_year',
                        'holiday_period_from' => '2026-09-01',
                        'holiday_period_to' => '2027-08-31',
                        'closed_weekdays' => [],
                        'closed_nth' => [],
                        'published_at' => '2026-08-01T10:00',
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'))
            ->assertSessionHasErrors(['new_news.new_1.closed_weekdays']);
    }

    public function test_holiday_period_is_required_for_holiday_category(): void
    {
        $this->actingAs($this->admin())
            ->from(route('admin.news.index'))
            ->put(route('admin.news.update'), [
                'new_news' => [
                    'new_1' => [
                        'title' => '定休日',
                        'body' => '',
                        'category' => 'holiday',
                        'published_at' => '2026-08-01T10:00',
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'))
            ->assertSessionHasErrors([
                'new_news.new_1.holiday_period_type',
                'new_news.new_1.holiday_period_from',
                'new_news.new_1.holiday_period_to',
            ]);
    }

    public function test_holiday_period_calendars_cover_from_to_months(): void
    {
        $salon = SalonSetting::current();
        $salon->closedWeekdays()->delete();
        $salon->closedNthWeekdays()->delete();
        $salon->closedWeekdays()->create(['weekday' => 2]);

        $news = $this->createNews([
            'title' => '期間定休日',
            'slug' => 'period-holiday',
            'category' => 'holiday',
            'holiday_period_type' => '3_months',
            'holiday_period_from' => '2026-09-01',
            'holiday_period_to' => '2026-11-30',
            'is_published' => true,
            'published_at' => '2026-08-15 10:00:00',
        ]);
        $news->closedWeekdays()->create(['weekday' => 2]);

        $this->assertTrue($news->coversBusinessCalendarMonth(2026, 9));
        $this->assertTrue($news->coversBusinessCalendarMonth(2026, 11));
        $this->assertFalse($news->coversBusinessCalendarMonth(2026, 8));
        $this->assertFalse($news->coversBusinessCalendarMonth(2026, 12));

        $payloads = News::businessCalendarsForPublicModal(collect([$news]));
        $this->assertArrayHasKey('2026-09', $payloads);
        $this->assertArrayHasKey('2026-10', $payloads);
        $this->assertArrayHasKey('2026-11', $payloads);
        $this->assertArrayNotHasKey('2026-08', $payloads);

        $september = $payloads['2026-09'];
        $this->assertArrayHasKey('2026-09-01', $september['days']); // Tuesday
        $this->assertContains('holiday', $september['days']['2026-09-01']);

        $modal = $news->toPublicModalData();
        $this->assertSame('2026/09/01 ～ 2026/11/30', $modal['holidayPeriodLabel']);
        $this->assertSame(['2026-09', '2026-10', '2026-11'], $modal['holidayPeriodKeys']);
        $this->assertSame('定休日は毎週火曜日です。', $modal['holidaySentence']);
    }

    public function test_temporary_closure_requires_at_least_one_closed_date(): void
    {
        $this->actingAs($this->admin())
            ->from(route('admin.news.index'))
            ->put(route('admin.news.update'), [
                'new_news' => [
                    'new_1' => [
                        'title' => '臨時休業',
                        'body' => '休業します。',
                        'category' => 'temporary_closure',
                        'closed_dates' => [],
                        'published_at' => '2026-08-01T10:00',
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'))
            ->assertSessionHasErrors(['new_news.new_1.closed_dates']);
    }

    public function test_new_card_markup_leaves_publish_state_unselected(): void
    {
        $html = $this->actingAs($this->admin())
            ->get(route('admin.news.index'))
            ->assertOk()
            ->getContent();

        $this->assertStringContainsString('novalidate', $html);
        $this->assertStringContainsString(
            "'<input type=\"radio\" name=\"new_news[' + key + '][is_published]\" value=\"1\" class=\"admin-segmented-input\" data-news-is-published>' +",
            $html
        );
        $this->assertStringNotContainsString(
            "'<input type=\"radio\" name=\"new_news[' + key + '][is_published]\" value=\"1\" class=\"admin-segmented-input\" data-news-is-published checked>' +",
            $html
        );
        $this->assertStringContainsString('fillPublishedAtIfEmpty', $html);
        $this->assertStringContainsString('const appTimezone =', $html);
        $this->assertStringContainsString('Asia\/Tokyo', $html);
        $this->assertStringContainsString('data-news-published-at', $html);
    }

    public function test_bulk_update_preserves_input_on_validation_errors(): void
    {
        $news = $this->createNews(['title' => '既存', 'slug' => 'existing']);

        $this->actingAs($this->admin())
            ->from(route('admin.news.index'))
            ->put(route('admin.news.update'), [
                'news' => [
                    $news->id => [
                        'title' => '',
                        'body' => '残す本文',
                        'category' => 'other',
                        'published_at' => '2026-08-01T09:00',
                        'is_published' => '1',
                        'display_order' => 1,
                    ],
                ],
                'new_news' => [
                    'new_1' => [
                        'title' => '新規入力途中',
                        'body' => '',
                        'category' => 'hours',
                        'published_at' => '2026-08-03T11:00',
                        'is_published' => '0',
                        'display_order' => 2,
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'))
            ->assertSessionHasErrors(['news.'.$news->id.'.title'])
            ->assertSessionDoesntHaveErrors(['new_news.new_1.body']);

        $this->assertSame('残す本文', session()->getOldInput('news.'.$news->id.'.body'));
        $this->assertSame('新規入力途中', session()->getOldInput('new_news.new_1.title'));
        $this->assertSame('2026-08-03T11:00', session()->getOldInput('new_news.new_1.published_at'));

        $html = $this->actingAs($this->admin())
            ->get(route('admin.news.index'))
            ->assertOk()
            ->getContent();

        $this->assertStringContainsString('残す本文', $html);
        $this->assertStringContainsString('新規入力途中', $html);
        $this->assertStringContainsString('name="new_news[new_1][title]"', $html);
        $this->assertStringContainsString('2026-08-03T11:00', $html);
    }

    public function test_validation_error_preserves_prepended_new_news_card_order(): void
    {
        $existing1 = $this->createNews([
            'title' => '既存1',
            'slug' => 'existing-1',
            'display_order' => 1,
        ]);
        $existing2 = $this->createNews([
            'title' => '既存2',
            'slug' => 'existing-2',
            'display_order' => 2,
        ]);

        $html = $this->actingAs($this->admin())
            ->followingRedirects()
            ->from(route('admin.news.index'))
            ->put(route('admin.news.update'), [
                'news' => [
                    $existing1->id => [
                        'title' => '既存1',
                        'body' => '本文1',
                        'category' => 'other',
                        'published_at' => '2026-08-01T10:00',
                        'is_published' => '1',
                        'display_order' => 2,
                    ],
                    $existing2->id => [
                        'title' => '既存2',
                        'body' => '本文2',
                        'category' => 'other',
                        'published_at' => '2026-08-01T11:00',
                        'is_published' => '1',
                        'display_order' => 3,
                    ],
                ],
                'new_news' => [
                    'new_1' => [
                        'title' => '先頭の新規',
                        'body' => '新規本文',
                        'category' => 'other',
                        'published_at' => '',
                        'is_published' => '0',
                        'display_order' => 1,
                    ],
                ],
            ])
            ->assertOk()
            ->assertSee('先頭の新規', false)
            ->getContent();

        preg_match('/id="news-grid"(.*?)<div\s+id="news-add-card"/s', $html, $matches);
        $this->assertNotEmpty($matches);
        $grid = $matches[1];

        $posNew = strpos($grid, 'data-news-new');
        $posExisting1 = strpos($grid, 'data-news-id="'.$existing1->id.'"');
        $posExisting2 = strpos($grid, 'data-news-id="'.$existing2->id.'"');

        $this->assertNotFalse($posNew);
        $this->assertNotFalse($posExisting1);
        $this->assertNotFalse($posExisting2);
        $this->assertLessThan($posExisting1, $posNew);
        $this->assertLessThan($posExisting2, $posExisting1);
    }

    public function test_bulk_update_normalizes_display_order(): void
    {
        $a = $this->createNews(['title' => 'A', 'slug' => 'a', 'display_order' => 10]);
        $b = $this->createNews(['title' => 'B', 'slug' => 'b', 'display_order' => 20]);

        $this->actingAs($this->admin())
            ->put(route('admin.news.update'), [
                'news' => [
                    $b->id => [
                        'title' => 'B',
                        'body' => 'body-b',
                        'category' => 'other',
                        'published_at' => '2026-08-01T10:00',
                        'display_order' => 1,
                        'is_published' => '1',
                    ],
                    $a->id => [
                        'title' => 'A',
                        'body' => 'body-a',
                        'category' => 'other',
                        'published_at' => '2026-08-01T10:00',
                        'display_order' => 2,
                        'is_published' => '1',
                    ],
                ],
            ])
            ->assertRedirect(route('admin.news.index'));

        $this->assertSame(1, $b->fresh()->display_order);
        $this->assertSame(2, $a->fresh()->display_order);
    }

    public function test_guest_cannot_access_news_admin(): void
    {
        $this->get(route('admin.news.index'))->assertRedirect();
        $this->put(route('admin.news.update'), [])->assertRedirect();
    }

    public function test_public_news_honors_display_order_and_published_rules(): void
    {
        SalonSetting::current();
        TopPageSection::ensureDefaults();

        $this->createNews([
            'title' => '後で表示',
            'slug' => 'second',
            'display_order' => 2,
            'is_published' => true,
            'published_at' => now()->subDay(),
        ]);
        $this->createNews([
            'title' => '先に表示',
            'slug' => 'first',
            'display_order' => 1,
            'is_published' => true,
            'published_at' => now()->subDays(5),
        ]);
        $this->createNews([
            'title' => '非公開',
            'slug' => 'draft',
            'display_order' => 0,
            'is_published' => false,
            'published_at' => now(),
        ]);
        $this->createNews([
            'title' => '未来公開',
            'slug' => 'future',
            'display_order' => 0,
            'is_published' => true,
            'published_at' => now()->addDay(),
        ]);

        $homeHtml = $this->get(route('home'))->assertOk()->getContent();
        $this->assertStringContainsString('先に表示', $homeHtml);
        $this->assertStringContainsString('後で表示', $homeHtml);
        $this->assertStringNotContainsString('非公開', $homeHtml);
        $this->assertStringNotContainsString('未来公開', $homeHtml);
        $this->assertLessThan(strpos($homeHtml, '後で表示'), strpos($homeHtml, '先に表示'));

        $listHtml = $this->get(route('news.index'))->assertOk()->getContent();
        $this->assertStringContainsString('先に表示', $listHtml);
        $this->assertLessThan(strpos($listHtml, '後で表示'), strpos($listHtml, '先に表示'));

        $this->get(route('news.show', 'first'))->assertOk()->assertSee('先に表示');
        $this->get(route('news.show', 'draft'))->assertNotFound();
        $this->get(route('news.show', 'future'))->assertNotFound();
    }
}
